# Capstone Project 1 - Statistics

At this point, you have obtained the data set for your Capstone project, cleaned and wrangled it into a form that's ready for analysis. It's now time to apply the inferential statistics techniques you have learned to explore the data. For example, are there variables that are particularly significant in terms of explaining the answer to your project question? Are there strong correlations between pairs of independent variables, or between an independent and a dependent variable?

In [3]:
# Import modules
import pandas as pd
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
from ggplot import *
import seaborn as sns
color = sns.color_palette()
%matplotlib inline
sns.set_context(rc={'figure.figsize': (16,12)})
pd.options.display.max_rows = 30

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
df = pd.read_csv('df.csv')
df.info()
df.head(3).transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79620 entries, 0 to 79619
Data columns (total 28 columns):
Unnamed: 0                79620 non-null int64
Unnamed: 0.1              79620 non-null int64
parcelid                  79620 non-null int64
logerror                  79620 non-null float64
transactiondate           79620 non-null object
year                      79620 non-null int64
month                     79620 non-null int64
num_bath                  79620 non-null float64
num_bed                   79620 non-null int64
fips                      79620 non-null float64
latitude                  79620 non-null float64
longitude                 79620 non-null float64
area_lot                  79620 non-null float64
zoning_county             79620 non-null object
zoning                    79620 non-null float64
rawcensustractandblock    79620 non-null float64
city                      79620 non-null int64
county                    79620 non-null float64
zip                       79620 non-null int64
num_rooms                 79620 non-null float64
build_year                79620 non-null int64
tax_assessed_structure    79620 non-null float64
tax_assessed_parcel       79620 non-null float64
assessmentyear            79620 non-null int64
tax_assessed_land         79620 non-null float64
tax_total                 79620 non-null float64
censustractandblock       79620 non-null float64
area_living               79620 non-null int64
dtypes: float64(15), int64(11), object(2)
memory usage: 17.0+ MB

                                  0            1            2
Unnamed: 0                        0            1            2
Unnamed: 0.1                   4176        11374        60917
parcelid                   12658092     12659026     12659032
logerror                     0.0507      -0.1661      -0.0471
transactiondate          2016-01-21   2016-02-24   2016-07-29
year                           2016         2016         2016
month                             1            2            7
num_bath                          2            2            3
num_bed                           2            2            3
fips                           6037         6037         6037
latitude                3.33393e+07    3.334e+07  3.33401e+07
longitude              -1.18331e+08 -1.18326e+08 -1.18326e+08
area_lot                       2080         1250         1103
zoning_county                  010D         0100         0100
zoning                          269          261          261
rawcensustractandblock   6.0376e+07   6.0376e+07   6.0376e+07
city                           3491         3491         3491
county                         3101         3101         3101
zip                           96207        96207        96207
num_rooms                         0            0            0
build_year                     1978         1920         1996
tax_assessed_structure       165947       300894       265712
tax_assessed_parcel          327635       545689       398565
assessmentyear                 2015         2015         2015
tax_assessed_land            161688       244795       132853
tax_total                   5433.63      7949.83      6174.19
censustractandblock      6.0376e+13   6.0376e+13   6.0376e+13
area_living                    1703          865         1500

In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df.rename(columns = {'Unnamed: 0.1': 'index_orig'}, inplace=True)

In [7]:
df.drop(['censustractandblock','fips','zoning','zoning_county','rawcensustractandblock'], axis=1, inplace=True)

In [8]:
df.head()
df.shape

,index_orig,parcelid,logerror,transactiondate,year,month,num_bath,num_bed,latitude,longitude,...,county,zip,num_rooms,build_year,tax_assessed_structure,tax_assessed_parcel,assessmentyear,tax_assessed_land,tax_total,area_living
0,4176,12658092,0.0507,2016-01-21,2016,1,2.0,2,33339295.0,-118331034.0,...,3101.0,96207,0.0,1978,165947.0,327635.0,2015,161688.0,5433.63,1703
1,11374,12659026,-0.1661,2016-02-24,2016,2,2.0,2,33340045.0,-118325943.0,...,3101.0,96207,0.0,1920,300894.0,545689.0,2015,244795.0,7949.83,865
2,60917,12659032,-0.0471,2016-07-29,2016,7,3.0,3,33340134.0,-118325615.0,...,3101.0,96207,0.0,1996,265712.0,398565.0,2015,132853.0,6174.19,1500
3,38326,12658206,-0.0182,2016-05-24,2016,5,2.0,2,33340239.0,-118324732.0,...,3101.0,96207,0.0,1964,89781.0,139956.0,2015,50175.0,3036.02,1422
4,72995,12659124,0.0421,2016-09-02,2016,9,2.0,2,33340508.0,-118324950.0,...,3101.0,96207,0.0,1965,103700.0,271000.0,2015,167300.0,5934.02,902

(79620, 22)

Correlations:
* logerror to number of bedrooms
* logerror to number of bathrooms
* logerror to sum of bedrooms and bathrooms
* logerror to living area
* logerror to lot area
* logerror to zip
* logerror to month

In [9]:
df.corr(method='pearson')

,index_orig,parcelid,logerror,year,month,num_bath,num_bed,latitude,longitude,area_lot,...,county,zip,num_rooms,build_year,tax_assessed_structure,tax_assessed_parcel,assessmentyear,tax_assessed_land,tax_total,area_living
index_orig,1.000000,-0.000130,0.011039,NaN,0.987659,-0.006013,-0.000869,0.010619,-0.011923,0.004006,...,0.007944,0.001384,-0.001462,0.004979,-0.004535,-0.008811,NaN,-0.009837,-0.017765,-0.006243
parcelid,-0.000130,1.000000,0.009560,NaN,-0.000903,0.009826,0.069835,-0.214342,-0.040715,-0.074303,...,-0.487620,0.037603,0.514535,0.120036,0.027213,0.021191,NaN,0.015310,-0.012316,0.062336
logerror,0.011039,0.009560,1.000000,NaN,0.011194,0.033590,0.027599,-0.002707,0.008970,0.005133,...,-0.013476,-0.002550,0.012200,0.023270,0.015296,0.002160,NaN,-0.004849,-0.015981,0.046956
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
month,0.987659,-0.000903,0.011194,NaN,1.000000,-0.005621,-0.000883,0.010164,-0.012098,0.004405,...,0.008604,0.001411,-0.002406,0.003571,-0.004190,-0.007942,NaN,-0.008814,-0.016398,-0.005117
num_bath,-0.006013,0.009826,0.033590,NaN,-0.005621,1.000000,0.630284,0.002334,-0.002798,0.005182,...,-0.074413,0.016157,0.045648,0.399042,0.606863,0.488260,NaN,0.363084,0.475626,0.778367
num_bed,-0.000869,0.069835,0.027599,NaN,-0.000883,0.630284,1.000000,0.003315,0.049267,-0.111061,...,-0.123597,0.023277,0.169838,0.107759,0.319093,0.242677,NaN,0.171520,0.241029,0.617893
latitude,0.010619,-0.214342,-0.002707,NaN,0.010164,0.002334,0.003315,1.000000,-0.538144,0.089686,...,0.551501,0.010871,-0.264492,0.071909,-0.034195,-0.134611,NaN,-0.168242,-0.103983,-0.047021
longitude,-0.011923,-0.040715,0.008970,NaN,-0.012098,-0.002798,0.049267,-0.538144,1.000000,-0.063857,...,-0.359617,0.032470,-0.002957,0.029643,-0.051791,-0.020046,NaN,-0.001150,-0.028235,0.018497
area_lot,0.004006,-0.074303,0.005133,NaN,0.004405,0.005182,-0.111061,0.089686,-0.063857,1.000000,...,0.107506,-0.003699,-0.084899,0.118446,0.009331,-0.021702,NaN,-0.034722,-0.022992,-0.048569
city,0.002916,-0.017828,0.001930,NaN,0.001958,-0.040172,-0.027171,-0.003774,0.005963,-0.011529,...,0.054386,-0.009616,-0.042516,-0.049146,-0.030621,-0.023158,NaN,-0.016280,-0.028534,-0.043727
county,0.007944,-0.487620,-0.013476,NaN,0.008604,-0.074413,-0.123597,0.551501,-0.359617,0.107506,...,1.000000,-0.059711,-0.757727,-0.230149,-0.054820,-0.088370,NaN,-0.093876,-0.043316,-0.158168
zip,0.001384,0.037603,-0.002550,NaN,0.001411,0.016157,0.023277,0.010871,0.032470,-0.003699,...,-0.059711,1.000000,0.048182,0.039385,0.004865,0.007938,NaN,0.008463,0.003984,0.028558
num_rooms,-0.001462,0.514535,0.012200,NaN,-0.002406,0.045648,0.169838,-0.264492,-0.002957,-0.084899,...,-0.757727,0.048182,1.000000,0.110957,-0.019325,0.020049,NaN,0.037558,-0.023991,0.106160
build_year,0.004979,0.120036,0.023270,NaN,0.003571,0.399042,0.107759,0.071909,0.029643,0.118446,...,-0.230149,0.039385,0.110957,1.000000,0.316730,0.154596,NaN,0.051190,0.126999,0.271989
tax_assessed_structure,-0.004535,0.027213,0.015296,NaN,-0.004190,0.606863,0.319093,-0.034195,-0.051791,0.009331,...,-0.054820,0.004865,-0.019325,0.316730,1.000000,0.825420,NaN,0.627075,0.792151,0.723025
tax_assessed_parcel,-0.008811,0.021191,0.002160,NaN,-0.007942,0.488260,0.242677,-0.134611,-0.020046,-0.021702,...,-0.088370,0.007938,0.020049,0.154596,0.825420,1.000000,NaN,0.957337,0.952157,0.600209
assessmentyear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tax_assessed_land,-0.009837,0.015310,-0.004849,NaN,-0.008814,0.363084,0.171520,-0.168242,-0.001150,-0.034722,...,-0.093876,0.008463,0.037558,0.051190,0.627075,0.957337,NaN,1.000000,0.908351,0.458095
tax_total,-0.017765,-0.012316,-0.015981,NaN,-0.016398,0.475626,0.241029,-0.103983,-0.028235,-0.022992,...,-0.043316,0.003984,-0.023991,0.126999,0.792151,0.952157,NaN,0.908351,1.000000,0.586031
area_living,-0.006243,0.062336,0.046956,NaN,-0.005117,0.778367,0.617893,-0.047021,0.018497,-0.048569,...,-0.158168,0.028558,0.106160,0.271989,0.723025,0.600209,NaN,0.458095,0.586031,1.000000

In [21]:
cp = df.corr(method='pearson').abs()

s = cp.unstack()
so = s.sort_values(kind="quicksort", ascending=False)
s

index_orig   index_orig                1.000000
             parcelid                  0.000130
             logerror                  0.011039
             year                           NaN
             month                     0.987659
             num_bath                  0.006013
             num_bed                   0.000869
             latitude                  0.010619
             longitude                 0.011923
             area_lot                  0.004006
             city                      0.002916
             county                    0.007944
             zip                       0.001384
             num_rooms                 0.001462
             build_year                0.004979
                                         ...
area_living  num_bed                   0.617893
             latitude                  0.047021
             longitude                 0.018497
             area_lot                  0.048569
             city                      0.043727
             county                    0.158168
             zip                       0.028558
             num_rooms                 0.106160
             build_year                0.271989
             tax_assessed_structure    0.723025
             tax_assessed_parcel       0.600209
             assessmentyear                 NaN
             tax_assessed_land         0.458095
             tax_total                 0.586031
             area_living               1.000000
dtype: float64

Strongest correlation to logerror is living area, but it's still only less than 5%.

In [11]:
df.corr(method='kendall')

,index_orig,parcelid,logerror,year,month,num_bath,num_bed,latitude,longitude,area_lot,...,county,zip,num_rooms,build_year,tax_assessed_structure,tax_assessed_parcel,assessmentyear,tax_assessed_land,tax_total,area_living
index_orig,1.000000,-0.002721,0.014600,NaN,0.947416,-0.003952,0.000340,0.007074,-0.007226,-0.000118,...,0.005537,0.001192,-0.001599,0.002695,-0.001797,-0.005069,NaN,-0.005882,-0.021923,-0.003640
parcelid,-0.002721,1.000000,0.019276,NaN,-0.003534,0.019924,0.096262,-0.391658,0.456066,-0.172523,...,-0.569672,0.281957,0.515069,0.109098,0.015043,0.065911,NaN,0.072905,0.015471,0.070151
logerror,0.014600,0.019276,1.000000,NaN,0.016152,0.049496,0.032240,-0.011306,0.011606,0.011359,...,-0.021184,0.015342,0.013108,0.030896,0.021508,0.019970,NaN,0.014372,-0.002983,0.051391
year,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
month,0.947416,-0.003534,0.016152,NaN,1.000000,-0.003681,0.000648,0.007221,-0.007793,-0.000081,...,0.006423,0.000630,-0.002289,0.002302,-0.001980,-0.004893,NaN,-0.005552,-0.022295,-0.002986
num_bath,-0.003952,0.019924,0.049496,NaN,-0.003681,1.000000,0.509033,0.013825,0.000010,0.134034,...,-0.094135,0.095461,0.046430,0.375633,0.505893,0.344752,NaN,0.212379,0.337574,0.623936
num_bed,0.000340,0.096262,0.032240,NaN,0.000648,0.509033,1.000000,-0.004377,0.062234,-0.010422,...,-0.155123,0.150273,0.169252,0.110773,0.276264,0.202611,NaN,0.124570,0.212180,0.560788
latitude,0.007074,-0.391658,-0.011306,NaN,0.007221,0.013825,-0.004377,1.000000,-0.442824,0.192779,...,0.371668,0.065178,-0.187906,0.035269,0.049108,-0.096610,NaN,-0.152257,-0.073367,-0.014957
longitude,-0.007226,0.456066,0.011606,NaN,-0.007793,0.000010,0.062234,-0.442824,1.000000,-0.120818,...,-0.301443,0.198470,0.113228,0.044016,-0.078588,-0.021770,NaN,-0.000329,-0.028291,0.027203
area_lot,-0.000118,-0.172523,0.011359,NaN,-0.000081,0.134034,-0.010422,0.192779,-0.120818,1.000000,...,0.192699,-0.013152,-0.101954,0.153011,0.137247,0.042884,NaN,-0.010220,0.042972,0.084438
city,-0.001155,0.169747,0.010852,NaN,-0.000985,0.009573,0.009619,-0.107747,0.064245,-0.033680,...,-0.123790,0.083238,0.108837,0.057050,0.019225,0.035072,NaN,0.034413,0.029163,-0.000081
county,0.005537,-0.569672,-0.021184,NaN,0.006423,-0.094135,-0.155123,0.371668,-0.301443,0.192699,...,1.000000,-0.434880,-0.748132,-0.194692,-0.050953,-0.132205,NaN,-0.136384,-0.070058,-0.157744
zip,0.001192,0.281957,0.015342,NaN,0.000630,0.095461,0.150273,0.065178,0.198470,-0.013152,...,-0.434880,1.000000,0.377005,0.265269,0.052211,-0.020317,NaN,-0.066054,-0.048164,0.112307
num_rooms,-0.001599,0.515069,0.013108,NaN,-0.002289,0.046430,0.169252,-0.187906,0.113228,-0.101954,...,-0.748132,0.377005,1.000000,0.088535,-0.020154,0.051877,NaN,0.063319,-0.005256,0.111764
build_year,0.002695,0.109098,0.030896,NaN,0.002302,0.375633,0.110773,0.035269,0.044016,0.153011,...,-0.194692,0.265269,0.088535,1.000000,0.353993,0.163457,NaN,0.044820,0.135878,0.204635
tax_assessed_structure,-0.001797,0.015043,0.021508,NaN,-0.001980,0.505893,0.276264,0.049108,-0.078588,0.137247,...,-0.050953,0.052211,-0.020154,0.353993,1.000000,0.587587,NaN,0.383059,0.529512,0.465911
tax_assessed_parcel,-0.005069,0.065911,0.019970,NaN,-0.004893,0.344752,0.202611,-0.096610,-0.021770,0.042884,...,-0.132205,-0.020317,0.051877,0.163457,0.587587,1.000000,NaN,0.795524,0.817601,0.350576
assessmentyear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
tax_assessed_land,-0.005882,0.072905,0.014372,NaN,-0.005552,0.212379,0.124570,-0.152257,-0.000329,-0.010220,...,-0.136384,-0.066054,0.063319,0.044820,0.383059,0.795524,NaN,1.000000,0.693342,0.230771
tax_total,-0.021923,0.015471,-0.002983,NaN,-0.022295,0.337574,0.212180,-0.073367,-0.028291,0.042972,...,-0.070058,-0.048164,-0.005256,0.135878,0.529512,0.817601,NaN,0.693342,1.000000,0.356084
area_living,-0.003640,0.070151,0.051391,NaN,-0.002986,0.623936,0.560788,-0.014957,0.027203,0.084438,...,-0.157744,0.112307,0.111764,0.204635,0.465911,0.350576,NaN,0.230771,0.356084,1.000000

In [12]:
ck = df.corr(method='kendall').abs()

s = ck.unstack()
sok = s.sort_values(kind="quicksort")
sok['logerror'].nlargest(2)

logerror       1.000000
area_living    0.051391
dtype: float64

Strongest correlation to logerror is still living area, but now it's just over 5%.

In [13]:
df.corr(method='spearman')

,index_orig,parcelid,logerror,year,month,num_bath,num_bed,latitude,longitude,area_lot,...,county,zip,num_rooms,build_year,tax_assessed_structure,tax_assessed_parcel,assessmentyear,tax_assessed_land,tax_total,area_living
index_orig,1.000000,-0.004103,0.021542,NaN,0.992451,-0.005334,0.000454,0.010605,-0.010862,-0.000159,...,0.006930,0.001791,-0.002068,0.004027,-0.002699,-0.007562,NaN,-0.008777,-0.033005,-0.005432
parcelid,-0.004103,1.000000,0.028497,NaN,-0.005086,0.021169,0.126256,-0.532192,0.489189,-0.259039,...,-0.758746,0.387459,0.654299,0.136818,0.021887,0.098889,NaN,0.111439,0.022118,0.101843
logerror,0.021542,0.028497,1.000000,NaN,0.022767,0.064465,0.042186,-0.016099,0.016308,0.017352,...,-0.026515,0.023034,0.016466,0.044556,0.030615,0.027931,NaN,0.020424,-0.005787,0.075118
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
month,0.992451,-0.005086,0.022767,NaN,1.000000,-0.004740,0.000832,0.010342,-0.011187,-0.000095,...,0.007684,0.000916,-0.002815,0.003288,-0.002835,-0.006980,NaN,-0.007918,-0.032055,-0.004253
num_bath,-0.005334,0.021169,0.064465,NaN,-0.004740,1.000000,0.580005,0.021449,-0.006205,0.179295,...,-0.106014,0.129981,0.044514,0.472902,0.636272,0.447449,NaN,0.281999,0.438864,0.754113
num_bed,0.000454,0.126256,0.042186,NaN,0.000832,0.580005,1.000000,-0.005670,0.079675,-0.024845,...,-0.174131,0.198499,0.184400,0.139700,0.362110,0.267625,NaN,0.166109,0.279356,0.689262
latitude,0.010605,-0.532192,-0.016099,NaN,0.010342,0.021449,-0.005670,1.000000,-0.618653,0.290081,...,0.489662,0.111898,-0.240204,0.059438,0.075094,-0.141435,NaN,-0.222742,-0.107979,-0.021972
longitude,-0.010862,0.489189,0.016308,NaN,-0.011187,-0.006205,0.079675,-0.618653,1.000000,-0.184077,...,-0.416875,0.304935,0.141494,0.052495,-0.117961,-0.033075,NaN,0.002551,-0.043313,0.036908
area_lot,-0.000159,-0.259039,0.017352,NaN,-0.000095,0.179295,-0.024845,0.290081,-0.184077,1.000000,...,0.241796,-0.016598,-0.133767,0.213136,0.207410,0.062683,NaN,-0.018309,0.061657,0.111415
city,-0.001695,0.266250,0.016036,NaN,-0.001388,0.012522,0.012362,-0.149853,0.126979,-0.049583,...,-0.154974,0.122852,0.134908,0.081563,0.028506,0.050968,NaN,0.049471,0.043026,-0.000546
county,0.006930,-0.758746,-0.026515,NaN,0.007684,-0.106014,-0.174131,0.489662,-0.416875,0.241796,...,1.000000,-0.570831,-0.803344,-0.244548,-0.062751,-0.165099,NaN,-0.169748,-0.087759,-0.198190
zip,0.001791,0.387459,0.023034,NaN,0.000916,0.129981,0.198499,0.111898,0.304935,-0.016598,...,-0.570831,1.000000,0.484444,0.378885,0.077224,-0.030399,NaN,-0.098699,-0.071459,0.167552
num_rooms,-0.002068,0.654299,0.016466,NaN,-0.002815,0.044514,0.184400,-0.240204,0.141494,-0.133767,...,-0.803344,0.484444,1.000000,0.105833,-0.027542,0.063804,NaN,0.079928,-0.008590,0.131498
build_year,0.004027,0.136818,0.044556,NaN,0.003288,0.472902,0.139700,0.059438,0.052495,0.213136,...,-0.244548,0.378885,0.105833,1.000000,0.494578,0.235449,NaN,0.065149,0.195318,0.294225
tax_assessed_structure,-0.002699,0.021887,0.030615,NaN,-0.002835,0.636272,0.362110,0.075094,-0.117961,0.207410,...,-0.062751,0.077224,-0.027542,0.494578,1.000000,0.766938,NaN,0.540566,0.704458,0.641825
tax_assessed_parcel,-0.007562,0.098889,0.027931,NaN,-0.006980,0.447449,0.267625,-0.141435,-0.033075,0.062683,...,-0.165099,-0.030399,0.063804,0.235449,0.766938,1.000000,NaN,0.940914,0.913620,0.500346
assessmentyear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tax_assessed_land,-0.008777,0.111439,0.020424,NaN,-0.007918,0.281999,0.166109,-0.222742,0.002551,-0.018309,...,-0.169748,-0.098699,0.079928,0.065149,0.540566,0.940914,NaN,1.000000,0.853563,0.339419
tax_total,-0.033005,0.022118,-0.005787,NaN,-0.032055,0.438864,0.279356,-0.107979,-0.043313,0.061657,...,-0.087759,-0.071459,-0.008590,0.195318,0.704458,0.913620,NaN,0.853563,1.000000,0.508265
area_living,-0.005432,0.101843,0.075118,NaN,-0.004253,0.754113,0.689262,-0.021972,0.036908,0.111415,...,-0.198190,0.167552,0.131498,0.294225,0.641825,0.500346,NaN,0.339419,0.508265,1.000000

In [14]:
cs = df.corr(method='spearman').abs()

s = cs.unstack()
sos = s.sort_values(kind="quicksort")
sos['logerror'].nlargest(2)

logerror       1.000000
area_living    0.075118
dtype: float64

Again, strongest correlation to logerror is living area, but now it is 7.5%, which is still weak.

Independent t-test for means
* logerror to number of bedrooms
* logerror to number of bathrooms
* logerror to sum of bedrooms and bathrooms
* logerror to living area
* logerror to lot area

For each of these t-tests, which will be performed as Welch's t-tests due to differing population variances, all null hypotheses are that the means are equal. P-values less than .05 will reject the null hypothesis in favor of the alternate, which is that the means are not equal.

In [15]:
a = df.logerror.abs()
b = df.num_bed
scipy.stats.ttest_ind(a,b,equal_var=False)

Ttest_indResult(statistic=-765.46081526807302, pvalue=0.0)

In [16]:
a = df.logerror.abs()
c = df.num_bath
scipy.stats.ttest_ind(a,c,equal_var=False)

Ttest_indResult(statistic=-623.30446933055987, pvalue=0.0)

In [17]:
a = df.logerror.abs()
d = df.num_bed + df.num_bath
scipy.stats.ttest_ind(a,d,equal_var=False)

Ttest_indResult(statistic=-783.64913785958436, pvalue=0.0)

In [18]:
a = df.logerror.abs()
e = df.area_living
scipy.stats.ttest_ind(a,e,equal_var=False)

Ttest_indResult(statistic=-539.7651697186127, pvalue=0.0)

In [19]:
a = df.logerror.abs()
f = df.area_lot
scipy.stats.ttest_ind(a,f,equal_var=False)

Ttest_indResult(statistic=-67.505422773089336, pvalue=0.0)

Because all p-values are 0.0, it appears that this test is inadequate. Will proceed with machine learning operations to see if there is any connection between the dependent variable (logerror) and the independent variables.

In [22]:
df.to_csv('df1.csv')